# -*- coding: utf-8 -*-
"""DSA_LL_implementation_LAb1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1szkCJpXabLNr9WGPFgfE-EQkymp9_hSC
"""

class Node: # this tells python how to build a new block called node
    def __init__(self, data): # this is a specia l setup function called constructor that runs automatically when we create a new node
        self.data = data #self represents the specific box being created rn
        self.next = None

    def __repr__(self):
        return f"Node({self.data})"

class LinkedList:
  def __init__(self):
    self.head = None  # tells that list is initially empty and no node is present so that we can point to

  def insertAtBeginning(self, new_data):
    new_node = Node(new_data) # this creates a new node
    new_node.next = self.head

  def printList(self):
     temp = self.head
     while temp:
        print(temp.data,end = ' ')
        temp = temp.next
     print()

  def insertAtEnd(self, new_data):
        new_node = Node(new_data)
        if self.head is None:
            self.head = new_node
            return
        last = self.head
        while last.next:
            last = last.next
        last.next = new_node


  def deleteFromBeginning(self):
    if self.head is None:
        return "The list is empty" # If the list is empty, return this string
    self.head = self.head.next  # Otherwise, remove the head by making the next node the new head


  def deleteFromEnd(self):
    if self.head is None:
        return "The list is empty"
    if self.head.next is None:
        self.head = None  # If there's only one node, remove the head by making it None
        return
    temp = self.head
    while temp.next.next:  # Otherwise, go to the second-last node
        temp = temp.next
    temp.next = None  # Remove the last node by setting the next pointer of the second-last node to None

if __name__ == '__main__':
  llist = LinkedList()

  llist.insertAtBeginning('1')
  llist.insertAtBeginning('10')
  llist.insertAtBeginning('100')
  llist.insertAtBeginning('1000')

  llist.insertAtEnd('200')
  llist.printList()

if __name__ == '__main__':
    llist = LinkedList()

    # Insert words at the beginning
    llist.insertAtBeginning('fox')
    llist.insertAtBeginning('brown')
    llist.insertAtBeginning('quick')
    llist.insertAtBeginning('the')

    # Insert a word at the end
    llist.insertAtEnd('jumps')

    # Print the list before deletion
    print("List before deletion:")
    llist.printList()

    # Deleting nodes from the beginning and end
    llist.deleteFromBeginning()
    llist.deleteFromEnd()

    # Print the list after deletion
    print("List after deletion:")
    llist.printList()

