# -*- coding: utf-8 -*-
"""circular queueipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19QJ3ZTXvOIk1PR3YpDDAU5nFalCCo-u7
"""

class CircularQueue:
    def __init__(self, capacity):
        self.capacity = capacity
        self.queue = [None] * capacity
        self.front = -1
        self.rear = -1

    def enqueue(self, item):
        if self.is_full():
            return "Queue is full"

        if self.front == -1:
            self.front = 0

        self.rear = (self.rear + 1) % self.capacity
        self.queue[self.rear] = item

    def dequeue(self):
        if self.is_empty():
            return "Queue is empty"

        item = self.queue[self.front]
        self.queue[self.front] = None

        if self.front == self.rear:
            self.front = -1
            self.rear = -1
        else:
            self.front = (self.front + 1) % self.capacity

        return item

    def peek(self):
        if self.is_empty():
            return "Queue is empty"
        return self.queue[self.front]

    def is_empty(self):
        return self.front == -1

    def is_full(self):
        return (self.rear + 1) % self.capacity == self.front

    def size(self):
        if self.is_empty():
            return 0

        if self.rear >= self.front:
            return self.rear - self.front + 1
        else:
            return self.capacity - self.front + self.rear + 1

q = CircularQueue(5)

q.enqueue(10)
q.enqueue(20)
q.enqueue(30)
q.enqueue(40)

print("Queue:", q.queue)
print("Front:", q.peek())

print("Deleted:", q.dequeue())
print("Deleted:", q.dequeue())

q.enqueue(50)
q.enqueue(60)

print("Queue:", q.queue)
print("Front:", q.peek())
print("Size:", q.size())