# -*- coding: utf-8 -*-
"""stack.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14WZh6hcl81tqvnqeWBQk95SsOb_4zvw6
"""

class Stack:
    def __init__(self):
        self.items = []

    def push(self, item):
        self.items.append(item)

    def pop(self):
        if self.is_empty():
            return "Stack Underflow"
        return self.items.pop()

    def peek(self):
        if self.is_empty():
            return "Stack is empty"
        return self.items[-1]

    def is_empty(self):
        return len(self.items) == 0

    def display(self):
        if self.is_empty():
            print("Stack is empty")
        else:
            print("Stack:", self.items)
s = Stack()
s.push(10)
s.push(20)
s.push(30)
s.display()
print("Top element:", s.peek())
print("Popped:", s.pop())
s.display()